dist: trusty
sudo: required

language: cpp

os:
  - linux
  - osx

compiler:
  - g++
  - clang++

env:
  - PLATFORM=x64 CONFIGURATION=Release

script:
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$CONFIGURATION -DTARGET_CPU=$PLATFORM
  - cmake --build . --config $CONFIGURATION
  - ctest -V --output-on-failure -ะก $CONFIGURATION

notifications:
  email: false